config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #1. list all tasks

  #show all tasks (get)
  get 'tasks' => 'tasks#index'

  # #2. create a task
  # #show form to gather user input(get)
  get 'tasks/new' => 'tasks#new'
  # #save newly created task to db (post)
  post 'tasks' => 'tasks#create'

  #1bis. show one task (get)
  get 'tasks/:id' => 'tasks#show', as: :task

  # #3. edit a task
  # #show form to gather user input (get)
  get 'tasks/:id/edit' => 'tasks#edit', as: :edit_task
  # #persist task to db (patch)
  patch 'tasks/:id' => 'tasks#update'

  #4. delete a task
  delete 'tasks/:id' => 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for (@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>List of Tasks</h1>
<h2><%= link_to "Add new task", tasks_new_path %></h2>
<% @tasks.each do |task| %>
  <ul>
    <li>Title: "<%= task.title %>"</li>
    <li>Completed status: <%= task.completed %></li>
    <li><%= link_to "show", task_path(task) %> <%= link_to "edit", edit_task_path(task) %></li>
    <li><%= link_to "delete (permanent!)", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %></li>
  </ul>
<% end %>

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p>Completed status: <%= @task.completed %></p>
<p><%= link_to "Back to tasks' list", tasks_path %></p>